# Generated by Django 5.1 on 2024-09-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='name',
        ),
    ]
